name: windows_autoclick
description: Autoclicker for windows.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_winapi: ^0.0.2

flutter:
  uses-material-design: true